<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\Application\Schedule.Application.Abstractions\Schedule.Application.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" />
      <PackageReference Include="FluentMigrator.Runner" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>

</Project>