services:
  postgres:
    image: postgres:latest
    container_name: dnd-schedule-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network